build: off

clone_folder: c:\gopath\src\github.com\kasvith\kache

environment:
  GOPATH: c:\gopath

stack: go 1.10

before_test:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/magefile/mage
  - mage vendor
  - mage fmt
  - mage vet
  - mage imports


test_script:
- mage test386
- mage testrace